- src: https://github.com/oatakan/ansible-role-ec2.git
  version: origin/master

- src: https://github.com/oatakan/ansible-role-vmware.git
  version: origin/master

- src: https://github.com/oatakan/ansible-role-azure.git
  version: origin/master

- src: https://github.com/oatakan/ansible-role-ovirt.git
  version: origin/master

- src: https://github.com/oatakan/ansible-role-kubevirt.git
  version: origin/master

- src: https://github.com/oatakan/ansible-role-openshift-add-auth-config.git
  version: origin/master
  name: oatakan.openshift-add-auth-config

- src: geerlingguy.nginx

- src: geerlingguy.mysql

- src: geerlingguy.haproxy